/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.digitalonus.blog.cassandra.ttl;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        
    }
}
